### ISSUE TITLE
docker-alpine base instead of busybox

### ISSUE THREAD

**Issue by pascalandy** [trayio/heka-logentries#2]
Hey guys, 

Curious about the base image. Would using https://github.com/gliderlabs/docker-alpine / https://hub.docker.com/r/gliderlabs/alpine/ be a good choice at the moment?

Would you expect any drawback ?

Cheers!

**Comment by lukaf** [comment]
Hi @pascalandy,

Heka needs GNU libc which isn't available in Alpine.

**Comment by pascalandy** [comment]
Thanks for letting me know! 

Cheers :)
